---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5be91f557892300011a20cf7/webhook/forestry'
sections:
  - type: document
    label: Config
    path: config.yaml
    templates:
      - config
  - type: document
    label: Home
    path: content/_index.md
    templates:
      - home
  - type: directory
    path: content/
    label: Pages
    create: all
    templates:
      - page
  - type: directory
    path: content/posts
    label: Posts
    create: all
    templates:
      - post
  - type: document
    label: Elements
    path: content/elements.md
    templates:
      - elements
upload_dir: static/uploads
public_path: /uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.47'
